/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentAttendeeCodeRouteImport } from './routes/tournament.$attendeeCode'
import { Route as AdminCodeRouteImport } from './routes/admin.$code'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentAttendeeCodeRoute = TournamentAttendeeCodeRouteImport.update({
  id: '/tournament/$attendeeCode',
  path: '/tournament/$attendeeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCodeRoute = AdminCodeRouteImport.update({
  id: '/admin/$code',
  path: '/admin/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/admin/$code': typeof AdminCodeRoute
  '/tournament/$attendeeCode': typeof TournamentAttendeeCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/admin/$code': typeof AdminCodeRoute
  '/tournament/$attendeeCode': typeof TournamentAttendeeCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/admin/$code': typeof AdminCodeRoute
  '/tournament/$attendeeCode': typeof TournamentAttendeeCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/admin/$code'
    | '/tournament/$attendeeCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/join' | '/admin/$code' | '/tournament/$attendeeCode'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/admin/$code'
    | '/tournament/$attendeeCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  AdminCodeRoute: typeof AdminCodeRoute
  TournamentAttendeeCodeRoute: typeof TournamentAttendeeCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$attendeeCode': {
      id: '/tournament/$attendeeCode'
      path: '/tournament/$attendeeCode'
      fullPath: '/tournament/$attendeeCode'
      preLoaderRoute: typeof TournamentAttendeeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$code': {
      id: '/admin/$code'
      path: '/admin/$code'
      fullPath: '/admin/$code'
      preLoaderRoute: typeof AdminCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  AdminCodeRoute: AdminCodeRoute,
  TournamentAttendeeCodeRoute: TournamentAttendeeCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
